added permission ABC-12

diff --git a/hooks/pre-receive b/hooks/pre-receive
--- a/hooks/pre-receive
+++ b/hooks/pre-receive
@@ -2,7 +2,7 @@
 check=$(head -1 $1 | grep -e '[A-Z]\+-[0-9]\+')
 if [ "" = "$check" ]; then
         echo "Commit message should have jira ticket id." 1>&2
-        echo "Required format:" 1>&2
+        echo "Required format is" 1>&2
         echo "    [ticketid] <description>" 1>&2
         exit 1
 fi
